config/routes.rb
Rails.application.routes.draw do
  resources :cups
  resources :owners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cup.rb
class Cup < ApplicationRecord
  belongs_to :owner
  validates :name, presence: true
  validate :validate_size

  def validate_size
    arr = ['small', 'medium', 'large']
    if arr.include?(self.size) == false
      errors.add(:size, 'No such cup size!')
    end
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cups
  validates :first_name, presence: true, uniqueness: true
  validates :last_name, presence: true, uniqueness: true
  validate :age_limit

  def full_name
    self.first_name + " " + self.last_name
  end

  def age_limit
    if self.age < 17
      errors.add(:age, 'Too young to be an owner')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  def index
    @cups = Cup.all
  end

  def show
    @cup = Cup.find(params[:id])
  end

  def new
    @cup = Cup.new
  end

  def create
    @cup = Cup.create(cup_params)
    if @cup.valid?
      flash[:message] = "Created Successfully!"
      redirect_to @cup
    else
      flash[:message] = "#{@cup.errors.full_messages[0]}"
      render :new
    end

  end

  def edit
    @cup = Cup.find(params[:id])

  end

  def update
    @cup = Cup.find(params[:id])
    @cup.update(cup_params)
    redirect_to @cup
  end

  def destroy
    @cup = Cup.find(params[:id])
    @cup.destroy
    redirect_to cups_path
  end
  private
    def cup_params
      params.require(:cup).permit(:name, :size, :owner_id)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.create(owner_params)
    if @owner.valid?
      flash[:message] = "Created Sucessfully!"
      redirect_to @owner
    else
      flash[:message] = "#{@owner.errors.full_messages}"
      render :new
    end
  end

  def edit
    @owner = Owner.find(params[:id])

  end

  def update
    @owner = Owner.find(params[:id])
    @owner.update(owner_params)
    redirect_to @owner
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy
    redirect_to owners_path
  end
  private
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :age, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cups_helper.rb
module CupsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/cups/edit.html.erb
<h1>Edit Cup</h1>
<%=form_for @cup do |f|%>
<%=f.label 'name'%>
<%=f.text_field 'name'%>
<br>
<%=f.label 'size'%>
<%=f.text_field 'size'%>
<br>
<%=f.collection_select(:owner_id, Owner.all, :id, :full_name)%>
<br>

<%=f.submit 'save'%>
<br>
<%end%>

app/views/cups/index.html.erb
<h1>All Cups</h1>
<ul>
<%@cups.each do |cup|%>
<li><%= link_to cup.name, cup_path(cup)%></li>

<%end%>
</ul>

app/views/cups/new.html.erb
<h1>New Cup</h1>

<% if  flash[:message]%>
<h1><%=flash[:message]%></h1>
<%end%>

<%=form_for @cup do |f|%>
<%=f.label 'name'%>
<%=f.text_field 'name'%>
<br>
<%=f.label 'size'%>
<%=f.text_field 'size'%>
<br>
<%=f.collection_select(:owner_id, Owner.all, :id, :full_name)%>
<br>

<%=f.submit 'add new cup'%>
<br>
<%end%>

app/views/cups/show.html.erb
<h1>This is <%=@cup.name%>'s cup page</h1>
<%=button_to "edit", edit_cup_path, method: :get%>
<%=button_to "delete", @cup, method: :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OwnerCupsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/edit.html.erb
<h1>Edit Owners</h1>
<%=form_for @owner do |f|%>
<%=f.label 'first_name'%>
<%=f.text_field 'first_name'%>
<br>
<%=f.label 'last_name'%>
<%=f.text_field 'last_name'%>
<br>
<%=f.label 'age'%>
<%=f.number_field 'age'%>
<br>
<%=f.label 'email'%>
<%=f.text_field 'email'%>
<br>
<%=f.submit 'edit'%>
<br>
<%end%>

app/views/owners/index.html.erb
<h1>All Owners</h1>
<ul>
<%@owners.each do |owner|%>
<li><%= link_to owner.full_name, owner_path(owner)%></li>

<%end%>
</ul>

app/views/owners/new.html.erb
<h1>New Owners</h1>
<% if flash[:message]%>
 <h2><%=flash[:message]%></h2>
<%end%>
<%=form_for @owner do |f|%>
<%=f.label 'first_name'%>
<%=f.text_field 'first_name'%>
<br>
<%=f.label 'last_name'%>
<%=f.text_field 'last_name'%>
<br>
<%=f.label 'age'%>
<%=f.number_field 'age'%>
<br>
<%=f.label 'email'%>
<%=f.text_field 'email'%>
<br>
<%=f.submit 'add new owner'%>
<br>
<%end%>

app/views/owners/show.html.erb
<h1>This is <%=@owner.full_name%>'s page</h1>
<%=button_to "edit", edit_owner_path, method: :get%>
<%=button_to "delete", @owner, method: :delete%>